### PR TITLE
Added UndoList.view function

### PR DESCRIPTION
**Pull request by TheSeamau5**
Implements view function as suggested here: https://github.com/TheSeamau5/elm-undo-redo/issues/4

@evancz  you'll like how this example now looks.

``` elm
import Html
import Html.Events exposing (onClick)
import Signal exposing (mailbox)
import UndoList exposing (UndoList, Action(..))

initial = 0

update _ state = state + 1

view address state =
  Html.div
      []
      [ Html.button
            [ onClick address (New ()) ]
            [ Html.text "Increment" ]
      , Html.button
            [ onClick address Undo ]
            [ Html.text "Undo" ]
      , Html.div
            []
            [ Html.text (toString state) ]
      ]

{address, signal} = mailbox Reset

main =
  Signal.map (UndoList.view view address)
    (Signal.foldp (UndoList.apply update) (UndoList.fresh initial) signal)
```

In this form, we can truly make the process painless. The only major changes are in the event handlers, but those changes are mandatory. Aside from that, by piling up all the transformations in the main function, we can truly have the initial model, the update function, and the view function unmodified.

### CODE REVIEW

**Comment by evancz** [comment]
This looks great! :) How do you feel about renaming `apply` to `update` to make it more parallel?

**Comment by TheSeamau5** [comment]
It does make more sense. I originally thought of `apply` as like applying an update. Cuz, rather than being an update function per-se, it's a function that takes an update function and returns an update function.

I guess that's true of the view function too... arghh.... 

Oh, well, I suppose consistency trumps cuteness ;) 

I mean, I could instead rename `view` to `applyPresent` but that would be too ugly and people would miss the point of it.

**Comment by evancz** [comment]
If you think of it as "an update function that takes an extra argument" and "a view function that takes an extra argument" I think the `view` and `update` names work nicely. It is a shame that `apply` seems to only work for one or the other!

**Comment by TheSeamau5** [comment]
All tests are green captain. `view` and `update` have boarded the ship and `apply` has walked the plank.

**Pull request merged**
