### PR TITLE
Try to make example and API explanation clearer

### PR DESCRIPTION
**Pull request by evancz**
Okay, this is a bigger change and it may look crazy, but give it a chance! :) I'm following some general rules that I think help:
- Mixing code and explanation heavily is often more confusing than helpful. I think the [Making Pong](http://elm-lang.org/blog/Pong.elm) is hurt by mixing text and code for such a long example. It _can_ work as code comments, but mixing text and code rarely works in my experience.
- Fewer words can often be way clearer, especially if you pick the right code examples and show code snippets in the right order and in such a way that you don't need much context besides the section header.
- People checking out the library want to see an example right out the gate, learning all the details is only necessary if you already decided you want to use it. With this PR, I juxtapose the before and after of the counter very directly. People can hop between and see it's really non-invasive. At that point they'll say, "what exactly is going on here?" and be met with the "More Details" section that gives insight into the particulars of how things work.

So the goal is to give increasing amounts of technical depth. This way people can't get lost before they understand the big picture. I think some of the text could be improved, but I think this general setup will work better for people.

### CODE REVIEW

**Comment by evancz** [comment]
Ah, I just realized that the `import Signal` line is not needed in either example anymore!

**Comment by evancz** [comment]
I'd say try to read the two of them side-by-side rendered as markdown to do a fair comparison. And maybe ask a programming friend which one is clearer for more data!

**Comment by TheSeamau5** [comment]
Wow, it does look better. It's like a no-nonsense intro to incorporating undo into your app. I like it.

Just update it to use records rather than union types cuz I already merged that change.

**Comment by evancz** [comment]
Okay, it has the record changes now. I think if we want to do the `StartApp` changes, it'd be easy to do them as a separate PR.

**Comment by TheSeamau5** [comment]
Yup, I think it's best. Here, I merged this PR, so feel free to work on those changes.

**Comment by evancz** [comment]
Cool, will do!

**Pull request merged**
