### PR TITLE
Just dotting some i's and crossing some t's

### PR DESCRIPTION
**Pull request by TheSeamau5**
@evancz  Just giving you a heads up on some minor stylistic/grammatical tweaks. I think everything looks fine. If you want to give it a final check before I merge, do so. After that, we can share this on Reddit, HN, etc...

### CODE REVIEW

**Comment by evancz** [comment]
Went to sleep for a while :) Timing for reddit and HN is important, you want it to be like 8am in NYC when you start things. So wait on it and we'll try to post it around then!

**Comment by TheSeamau5** [comment]
@evancz Time to post it?

**Comment by evancz** [comment]
Yeah, I think so! Are you going to post to /r/programming? I'll tweet about it as well, which seems to help with HN.

**Comment by evancz** [comment]
Are you on twitter?

**Comment by TheSeamau5** [comment]
yeah, i just never use it https://twitter.com/TheSeaMouse

**Comment by evancz** [comment]
Also, I think you should go with "Add undo/redo to any Elm app with just a few lines of code" as the title.

**Comment by TheSeamau5** [comment]
There, it got tweeted, posted to HN, and r/programming

**Pull request merged**
